
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AplikasiCekCuacaSederhana extends javax.swing.JFrame {

    // Konstanta API dan path file
    private static final String API_KEY = "e988bb67d693fdf64a31d63b503d0726"; // API key untuk OpenWeatherMap
    private static final String API_URL = "http://api.openweathermap.org/data/2.5/weather"; // URL API cuaca
    private static final String CITY_LIST_FILE = System.getProperty("user.dir") + "/data/kota_pilihan.txt"; // Path untuk daftar kota
    private static final String CUACA_DATA_FILE = System.getProperty("user.dir") + "/data/cuaca_data.csv"; // Path untuk data cuaca
    
    private DefaultTableModel modelTabelCuaca; // Model tabel untuk menampilkan data cuaca
    
    public AplikasiCekCuacaSederhana() {
        initComponents();
        cekAtauBuatFolderData(); // Cek atau buat folder 'data'
        muatKotaDariFile(); // Muat data kota yang tersimpan dari file
        modelTabelCuaca = new DefaultTableModel(new String[]{"Kota", "Cuaca", "Suhu"}, 0);
        TabelCuaca.setModel(modelTabelCuaca); // Pasang model tabel pada jTable1
    }
    
          // Ambil data cuaca dari API berdasarkan kota
    private String mengambilData(String kota) {
        String result = "";
        try {
            // Buat URL lengkap dengan parameter API dan kota
            String urlString = API_URL + "?q=" + kota + ",id&appid=" + API_KEY + "&units=metric&lang=id";
            URL url = new URL(urlString);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");

            // Periksa respon dari server
            int responseCode = conn.getResponseCode();
            if (responseCode == 200) {
                BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                StringBuilder sb = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    sb.append(line);
                }
                reader.close();
                result = sb.toString();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mendapatkan data cuaca. Kode respons: " + responseCode);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan koneksi: " + e.getMessage());
            e.printStackTrace();
        }
        return result;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelMasukkanNamaKota = new javax.swing.JLabel();
        FieldMasukkanNamaKota = new javax.swing.JTextField();
        TombolCekCuaca = new javax.swing.JButton();
        LabelKeadaanCuaca = new javax.swing.JLabel();
        DeskripsiCuaca = new javax.swing.JLabel();
        LabelSuhu = new javax.swing.JLabel();
        LabelPilihKota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelCuaca = new javax.swing.JTable();
        TombolSimpanCuaca = new javax.swing.JButton();
        TombolMemuatData = new javax.swing.JButton();
        ComboBoxKota = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Cek Cuaca");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Cek Cuaca");

        LabelMasukkanNamaKota.setText("Masukkan Nama Kota : ");

        FieldMasukkanNamaKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMasukkanNamaKotaActionPerformed(evt);
            }
        });

        TombolCekCuaca.setText("Cek Cuaca");
        TombolCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolCekCuacaActionPerformed(evt);
            }
        });

        LabelKeadaanCuaca.setText("Keadaan Cuaca :");

        DeskripsiCuaca.setText("Deskripsi Cuaca : ");

        LabelSuhu.setText("Suhu Saat Ini : ");

        LabelPilihKota.setText("Pilih Kota : ");

        TabelCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelCuaca);

        TombolSimpanCuaca.setText("Simpan Data Cuaca");
        TombolSimpanCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanCuacaActionPerformed(evt);
            }
        });

        TombolMemuatData.setText("Memuat Data Cuaca");
        TombolMemuatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolMemuatDataActionPerformed(evt);
            }
        });

        ComboBoxKota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxKotaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelMasukkanNamaKota)
                                .addGap(70, 70, 70)
                                .addComponent(FieldMasukkanNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelPilihKota)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBoxKota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TombolMemuatData)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(TombolCekCuaca))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(TombolSimpanCuaca))))
                    .addComponent(LabelKeadaanCuaca)
                    .addComponent(DeskripsiCuaca)
                    .addComponent(LabelSuhu))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMasukkanNamaKota)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FieldMasukkanNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TombolCekCuaca)))
                .addGap(36, 36, 36)
                .addComponent(LabelKeadaanCuaca)
                .addGap(18, 18, 18)
                .addComponent(DeskripsiCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSuhu)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelPilihKota)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(TombolMemuatData)))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolSimpanCuaca)
                        .addGap(147, 147, 147))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldMasukkanNamaKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMasukkanNamaKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMasukkanNamaKotaActionPerformed

    private void TombolCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolCekCuacaActionPerformed
        // TODO add your handling code here:
        String namakota = FieldMasukkanNamaKota.getText();
        if (!namakota.isEmpty()) {
            MenampilkanCuaca(namakota);

            boolean kotaTersedia = false;
            for (int i = 0; i < ComboBoxKota.getItemCount(); i++) {
                if (ComboBoxKota.getItemAt(i).equalsIgnoreCase(namakota)) {
                    kotaTersedia = true;
                    break;
                }
            }

            if (!kotatersedia) {
                ComboBoxKkota.addItem(namakota);
                simpanKotaKeFile(); // Simpan kota ke file setelah menambahkannya
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silakan Memasukkan Nama Kota!!");
        }
    }          
    }//GEN-LAST:event_TombolCekCuacaActionPerformed

    private void TombolSimpanCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanCuacaActionPerformed
        // TODO add your handling code here:
        String namakota = FieldMasukkanNamaKota.getText();
        String deskripsiCuaca = DeskripsiCuaca.getText();
        String suhu = LabelSuhu.getText().replace("°C", "");

        if (!namakota.isEmpty() && !deskripsiCuaca.isEmpty() && !suhu.isEmpty()) {
            double suhu = Double.parseDouble(suhu);
            SimpanDataKeFile(namakota, deskripsiCuaca, suhu);
        } else {
            JOptionPane.showMessageDialog(this, "Data cuaca tidak lengkap. Pastikan semua data sudah terisi.");
        }               
    }//GEN-LAST:event_TombolSimpanCuacaActionPerformed

    private void TombolMemuatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolMemuatDataActionPerformed
        // TODO add your handling code here:
        try (BufferedReader reader = new BufferedReader(new FileReader("data/cuaca_data.csv"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 3) {
                    // Menambahkan data ke dalam tabel
                    modelTabelCuaca.addRow(new Object[]{data[0], data[1], data[2]});
                }
            }
            JOptionPane.showMessageDialog(this, "Data cuaca berhasil dimuat ke tabel.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data cuaca.");
            e.printStackTrace();
        }             
    }//GEN-LAST:event_TombolMemuatDataActionPerformed

    private void ComboBoxKotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxKotaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String kotaDipilih = (String) ComboBoxKoa.getSelectedItem();
            FieldMasukkanNamaKota.setText(kotaDipilih);
            MenampilkanCuaca(kotaDipilih);
        }
    }//GEN-LAST:event_ComboBoxKotaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiCekCuacaSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxKota;
    private javax.swing.JLabel DeskripsiCuaca;
    private javax.swing.JTextField FieldMasukkanNamaKota;
    private javax.swing.JLabel LabelKeadaanCuaca;
    private javax.swing.JLabel LabelMasukkanNamaKota;
    private javax.swing.JLabel LabelPilihKota;
    private javax.swing.JLabel LabelSuhu;
    private javax.swing.JTable TabelCuaca;
    private javax.swing.JButton TombolCekCuaca;
    private javax.swing.JButton TombolMemuatData;
    private javax.swing.JButton TombolSimpanCuaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
